-- Motoboys / entregadores.
CREATE TABLE IF NOT EXISTS couriers (
    id            INT UNSIGNED NOT NULL AUTO_INCREMENT,
    company_id    INT UNSIGNED NOT NULL,
    name          VARCHAR(150) NOT NULL,
    phone         VARCHAR(20)  NOT NULL,
    email         VARCHAR(150) DEFAULT NULL,
    password_hash VARCHAR(255) DEFAULT NULL,
    document      VARCHAR(20)  DEFAULT NULL,
    vehicle       ENUM('moto','bike','car') NOT NULL DEFAULT 'moto',
    plate         VARCHAR(10)  DEFAULT NULL,
    selfie_url    VARCHAR(255) DEFAULT NULL,
    document_url  VARCHAR(255) DEFAULT NULL,
    status        ENUM('offline','online','busy','suspended') NOT NULL DEFAULT 'offline',
    lat           DECIMAL(10,7) DEFAULT NULL,
    lng           DECIMAL(10,7) DEFAULT NULL,
    heading       SMALLINT UNSIGNED DEFAULT NULL,
    rating        DECIMAL(3,2) NOT NULL DEFAULT 5.00,
    balance       DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    total_deliveries INT UNSIGNED NOT NULL DEFAULT 0,
    is_verified   TINYINT(1) NOT NULL DEFAULT 0,
    last_seen_at  DATETIME DEFAULT NULL,
    created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_courier_company (company_id),
    KEY idx_courier_status (company_id, status),
    KEY idx_courier_geo (lat, lng),
    CONSTRAINT fk_courier_company FOREIGN KEY (company_id) REFERENCES companies (id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
